### ISSUE TITLE
bundle install fails when generating with --project-type ruby-rails

### ISSUE THREAD

**Issue by joeyAghion** [artsy/hokusai#18]
A fresh Rails project fails to `bundle install` during `hokusai dev`.

Adding this to the generated `Dockerfile` (right after the `apt-get update`) fixes it:

    apt-get install -y nodejs

**Comment by izakp** [comment]
@joeyAghion Is NodeJS now a core Rails dependency?  If so, moving forward, then yea let's add it.

**Comment by izakp** [comment]
Fixed via 82b4b18996074587bd286995536a32474bfa0f97

**Comment by izakp** [comment]
Fixed via https://github.com/artsy/hokusai/commit/f27db8bedca9e037bf473864a806f00a30c0261a
