### ISSUE TITLE
Support copying secrets from one namespace to another

### ISSUE THREAD

**Issue by jonallured** [artsy/hokusai#181]
I hadn't created a review app in a while but then last week I was working on this with @oxaudo and found that copying secrets was pretty painful. I asked in the hokusai Slack channel and there isn't currently a command to automate this, but it sound like there was so I'm opening this ticket to track that work.

https://artsy.slack.com/archives/CE4ENV8QZ/p1571948381000500

**Comment by artsyjian** [comment]
Looking over outstanding issues. Looks like this one was addressed?

`hokusai review_app create` command [takes care](https://github.com/artsy/hokusai/blob/d169cd8857d37a3a00ef3ce90edb453f56310163/hokusai/commands/kubernetes.py#L137) of copying ConfigMap from `default` namespace to the Review App's namespace.

**Comment by jonallured** [comment]
Oh nice - thanks for following up @artsyjian !! 🏆
