### ISSUE TITLE
Should RAILS_ENV be production in staging?

### ISSUE THREAD

**Issue by joeyAghion** [artsy/hokusai#19]
There's no official `staging` environment supported in Rails. Starting a project with `RAILS_ENV=staging` would require creating a new `config/environments/staging.rb` file (presumably similar to production.rb) and potentially impact gems (that might test for `Rails.env.production?` or even bundler (that might not load gems from the `:production` group). 

It's recommended instead that staging apps use `RAILS_ENV=production`, with any different behaviors controlled by environment variables (see below links). I suggest that hokusai generate its `staging.yml` template with `RAILS_ENV=production`.

https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment
https://devcenter.heroku.com/articles/multiple-environments

**Comment by izakp** [comment]
👍

**Comment by izakp** [comment]
Fixed via https://github.com/artsy/hokusai/commit/f27db8bedca9e037bf473864a806f00a30c0261a
