### ISSUE TITLE
Dockerfile and ENV updates to serve assets

### ISSUE THREAD

**Issue by joeyAghion** [artsy/hokusai#20]
I ran into a few hiccups when setting up a Rails project for the first time.

(1) To ensure that fingerprinted asset files are generated and available for serving from within the container, I had to add this to the `Dockerfile` after the `WORKDIR` command:

    RUN bundle exec rake assets:precompile

Note that this slows down dev/test commands significantly, and isn't strictly required in those contexts. Maybe there's a better formulation for this?

(2) I also had to add this ENV var indicating that Rails should serve static files (since it's often behind an Nginx/Apache web server that serves static files directly, this isn't the default):

    hokusai env set RAILS_SERVE_STATIC_FILES=true --staging

To be honest, I'm not sure where suggested ENV values should go in the `hokusai` workflow, since there's no "default" configMap. Maybe they should go into the `staging.yml` and `production.yml` templates, or at least be documented?

**Comment by joeyAghion** [comment]
Note that the `RAILS_SERVE_STATIC_FILES` environment variable is only respected in Rails 4.2+, but I think it's reasonable to assume new Hokusai projects are compatible.

**Comment by izakp** [comment]
@joeyAghion as far as running `bundle exec rake assets:precompile` I don't see a way to get around always running this unless we split Dockerfiles for dev / prod.  I suppose we should add this to the default template though.

I need to write up a GettingStarted.md or some similar guide to document the order in which commands should be run.  Basically you should do a `hokusai env create --staging` then a `hokusai env set RAILS_SERVE_STATIC_FILES=true --staging` before a `hokusai stack create --staging` and you'll be good to go.

**Comment by izakp** [comment]
Fixed via https://github.com/artsy/hokusai/commit/f27db8bedca9e037bf473864a806f00a30c0261a
