### ISSUE TITLE
Pyinstaller build broken for 0.58 / 0.59

### ISSUE THREAD

**Issue by izakp** [artsy/hokusai#203]
```
[4072] Error loading Python lib '/tmp/_MEIpronl1/libpython2.7.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIpronl1/libp
ython2.7.so.1.0)
```

As observed on 
```
ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
```

**Comment by izakp** [comment]
Possible that the `python:2` [image](https://hub.docker.com/layers/python/library/python/2/images/sha256-c934af72b8bd03b9804d5bde2569c320926e70392d708d113a2e71bcf98c8a20?context=explore) is responsible as Pyinstaller is built in it and this error is not observed on 0.5.7

**Comment by artsyjian** [comment]
Closing issue since Hokusai [no longer supports Python2](https://github.com/artsy/hokusai/pull/285) and this problem is not observed on Python3.
