### ISSUE TITLE
Configure Rails stacks to log to STDOUT

### ISSUE THREAD

**Issue by joeyAghion** [artsy/hokusai#21]
When setting up a Rails stack for the first time, I was puzzled that requests weren't appearing in the Kubernetes logs. It turns out I had to enable logging to STDOUT via:

    hokusai env set RAILS_LOG_TO_STDOUT=true --staging

Much like https://github.com/artsy/hokusai/issues/20, I'm not sure if this should go into the default `.yml` files generated for Rails projects or just be documented.

And the ENV var is only respected starting in Rails 5. Earlier projects will need the [rails_12factor](https://github.com/heroku/rails_12factor) gem.

**Comment by izakp** [comment]
Fixed via https://github.com/artsy/hokusai/commit/f27db8bedca9e037bf473864a806f00a30c0261a
