### ISSUE TITLE
setup fails with ECR permission errors

### ISSUE THREAD

**Issue by bhoggard** [artsy/hokusai#27]
When I run

    hokusai setup --aws-account-id <redacted> 2 --project-type elixir

I get an error message:

    ERROR: An error occurred (AccessDeniedException) when calling the DescribeRepositories operation: User: arn:aws:iam::<redacted>:user/barry is not authorized to perform: ecr:DescribeRepositories on resource: *

However, I can run this command successfully:

    aws ecr describe-repositories

**Comment by izakp** [comment]
This will happen when using an `--aws-account-id` you do not have `ecr:DescribeRepositories` permissions for via your IAM credentials.

**Comment by bhoggard** [comment]
Never mind, I had the wrong account number for my credentials.
