### ISSUE TITLE
Add an alias for --follow  as --tail in `dev logs`

### ISSUE THREAD

**Issue by orta** [artsy/hokusai#32]
I would have expected `--tail` to be how I can track logs as hokusai aims to feel like heroku. I get that `--follow` makes sense because it's what docker's CLI uses, so why not have both?

**Comment by izakp** [comment]
@orta although I initially implemented this alias, it occurs to me that, although heroku considers `follow` and `tail` as aliases, they actually do have distinct semantics (think of the bash command `tail`) that are respected by [kubectl logs](https://kubernetes.io/docs/user-guide/kubectl/v1.6/#logs) as well as [docker-compose logs](https://docs.docker.com/compose/reference/logs/) - i.e. `follow` meaning "Specify if the logs should be streamed" and `tail` meaning "(Number of) Lines of recent log file to display."

I will add the option `--tail` to pass through to both.

cc @damassi

**Comment by izakp** [comment]
Closed via https://github.com/artsy/hokusai/pull/40
