### ISSUE TITLE
image built on Mac M1 fails to run on Intel servers

### ISSUE THREAD

**Issue by artsyjian** [artsy/hokusai#339]
Docker images built with `hokusai build` on a Mac M1 machine, when run on Intel server, fails with:

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

This problem affects environments where users' local workstations' CPU architecture differ from their Staging/Production servers.

**Comment by artsyjian** [comment]
The ideal solution seems to be for Hokusai to build [multi-platform images](https://docs.docker.com/build/building/multi-platform/). Specifically, to build an image that contains variants for `linux/amd64` and `linux/arm64`. The ARM64 variant covers developers' M1 workstations, while the AMD64 one covers Intel Mac's and x86_64 Kubernetes servers.

This is likely not hard to do in a CI pipeline, where servers are controlled. But it seems hard to achieve when building image on a developer's local workstation, for a Review App, which is how this problem surfaced.

As it is, Review App creation for most projects are done manually and locally. Hokusai will have to be concerned about workstation CPU architecture (Intel, M1), Buildkit support, and whether a project's Dockerfile even works in an ARM64 build. It seems a lot of work has to be done before attempting multi-platform builds.

I think for now the only feasible solution is to have `hokusai build` force x86_64 (via [DOCKER_DEFAULT_PLATFORM=linux/amd64](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables) env var when [calling](https://github.com/artsy/hokusai/blob/3b86834c1cfdd652cf17d4ad34e1b4dd3f39721f/hokusai/services/docker.py#L20) `docker-compose build`). On an M1 workstation, the build does work, and the resulting image does run, meaning [Docker Desktop](https://docs.docker.com/desktop/install/mac-install/) on M1 does support AMD64. And let Hokusai continue the assumption that the build machine's CPU architecture match that of the Kubernetes servers.

**Comment by joeyAghion** [comment]
> On an M1 workstation, the build does work, and the resulting image does run, meaning [Docker Desktop](https://docs.docker.com/desktop/install/mac-install/) on M1 does support AMD64.

☝️ Exactly what I came here to ask.
