### ISSUE TITLE
Should migrations be part of hokusai config?

### ISSUE THREAD

**Issue by izakp** [artsy/hokusai#37]
That way they wouldn't have to be passed in as the `--migration` flag to a `deploy` or `promote` command.  cc @ashkan18

**Comment by ashkan18** [comment]
This is actually an awesome idea, we could add a `post_deploy` or `pre_deploy` config! i think this makes lot of sense knowing i've personally forgot running migrations few times already.

**Comment by izakp** [comment]
Excellent :)  I am leaning towards having as much as we can regarding the CI workflow specified in config.

**Comment by izakp** [comment]
Closed via https://github.com/artsy/hokusai/pull/40
