### ISSUE TITLE
Gracefully fail when run with missing configuration

### ISSUE THREAD

**Issue by ashfurrow** [artsy/hokusai#47]
I had installed the dependencies and Hokusai but had skipped the `hokusai configure ...` step (my fault). But I got some nondescriptive errors:

```sh
➜ hokusai staging  status

Deployments
-----------------------------------------------------------
error: context "staging" does not exist
ERROR: Command 'kubectl --context staging get deployments --selector app=currents -o wide' returned non-zero exit status 1
➜  kubectl --context staging get deployments --selector app=currents -o wide
error: context "staging" does not exist
```

Is there an opportunity to provide more descriptive feedback, like "I couldn't connect to the cluster" or "I haven't been configured yet" or something?

**Comment by izakp** [comment]
@ashfurrow there is a check for the context "staging" existing in your kubectl config file when running `hokusai check` but I suppose it makes sense to check for it inline in other commands.  Thanks!
