### ISSUE TITLE
`hokusai check` fails due to unset kubectl context

### ISSUE THREAD

**Issue by javamonn** [artsy/hokusai#82]
I installed and configured `hokusai` according to our internal Artsy docs.

Running `hokusai check` unexpectedly fails on `kubectl not found`, though `kubectl` is installed correctly. Hokusai appears to work correctly even though the check fails. The issue appears to be that the check runs `kubectl version`, which returns a non-zero exit code as `kubectl config current-context` is unset.

The exact output I get from running `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: dial tcp: lookup localhost on 8.8.8.8:53: no such host
```

**Comment by izakp** [comment]
Closed via https://github.com/artsy/hokusai/pull/93
