### ISSUE TITLE
Option to enable tty by default?

### ISSUE THREAD

**Issue by ashfurrow** [artsy/hokusai#83]
I realized today that I've never _not_ wanted to run `--tty` when running a command on our cluster. What do you think about an environment variable I can set so I don't have to include it each time? Let me know and I can send a PR 👍

**Comment by izakp** [comment]
In any case I would follow the naming conventions from Click's automatic support of ENV vars as options.  From the docs:

> Each command and parameter is then added as an uppercase underscore-separated variable. If you have a subcommand called foo taking an option called bar and the prefix is MY_TOOL, then the variable is MY_TOOL_FOO_BAR

So the env var in the case of calling Hokusai's run command would IMHO make sense as `HOKUSAI_RUN_TTY` (as run is a single nested subcommand present in both the staging and production command groups)

**Comment by izakp** [comment]
Closed via https://github.com/artsy/hokusai/pull/101
