### ISSUE TITLE
Warning when running an outdated version

### ISSUE THREAD

**Issue by izakp** [artsy/hokusai#86]
@alloy Not sure how to approach this other than checking https://pypi.org/project/hokusai/#history every time Hokusai runs, which seems excessive

Perhaps somehow tying it to the project config would be better

**Comment by alloy** [comment]
Yeah good question. Maybe we can identify certain commands where it really matters? I assume there’s no other requests that are regularly made anyways that we could piggy-back off?

**Comment by dblandin** [comment]
What if we were to track releases via GitHub and check once every X interval (hour, day, etc) across any Hokusai command?

Upon any command execution, if we haven't checked within the past X interval, hit the GitHub API and compare versions. If the local Hokusai is out of date, show a warning? Maybe prompt to upgrade or continue?

https://api.github.com/repos/artsy/hokusai/releases/latest

**Comment by alloy** [comment]
Yeah good point, at most once an hour is probably a good interval, but then I do think we should do it synchronously before the command does any other work and maybe even ask:

```
There’s a new version, are you sure you want to continue this with an outdated version? [y/N]
```

**Comment by dblandin** [comment]
> I do think we should do it synchronously before the command does any other work and maybe even ask

I like that! :+1:

**Comment by artsyjian** [comment]
closing in favor of https://github.com/artsy/hokusai/issues/150
